name: advanced_weather_app01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Existing packages from your repo
  geolocator: ^10.0.0
  http: ^1.2.3
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.68.0

  # New packages for requirements
  sqflite: ^2.2.8+4
  path: ^1.8.4
  crypto: ^3.0.7
  sqflite_common_ffi: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/weather.png
